# Site configuration for production
# _config.yml
# default configuration: https://jekyllrb.com/docs/configuration/default/

# Server

url: "https://glegoux.com"
baseurl: ""
detach: false
show_dir_listing: false
encoding: "utf-8"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
      article: true
  - scope:
      path: "static/img"
    values:
      image: true

# GitHub

github: ["metadata"]

highlighter: rouge

gist:
  noscript: true

# SEO

title: "Software Engineering Blog - Gilles Legoux"
description: "Personal blog about software engineering"
author: "Gilles Legoux"
keywords: "glegoux,Gilles,Legoux,informatics,mathematics"
logo: "/static/img/icon-iphone.png"
lang: "en"

# Articles

paginate: 12
paginate_path: "/blog/articles/:num/"
permalink: "/blog/articles/:year/:month/:day/:title:output_ext"

# Build

source: "."
data_dir: "./_data"
layouts_dir: "./_layouts"
includes_dir: "./_includes"
plugins_dir: "./_plugins"
destination: "./_site"

show_drafts: false

sass:
  sass_dir: "_sass"
  style: "compressed"

exclude:
  - "bin/"
  - "CNAME"
  - "Makefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "VERSION"
  - "LICENSE"

# Plugins

plugins:
  - "jekyll-sitemap"
  - "jekyll-seo-tag"
  - "jekyll-github-metadata"
  - "jekyll-redirect-from"
  - "jekyll-paginate"
  - "jemoji"
