blog:
  title_header: "@GillesLegoux (glegoux)"
  title: "Software Engineering"
  keywords: ["Research & Development", "Algorithm", "Data", "Machine Learning", "Web", "Security", "Applied Mathematics", "Reliability & Infrastructure", "Design", "System", "Methodology", "Business"]
article:
  static: "https://cdn.jsdelivr.net/gh/glegoux/articles-glegoux-com@master/articles"
  source: "https://raw.githubusercontent.com/glegoux/glegoux.github.io/master/_posts"
  image:
    path: "images"
    suffix: ""
google_analytics:
  code: "UA-155162630-1"
disqus_name: "glegoux-com"
libs:
  version:
    jquery: "3.4.1"
    popper: "1.14.3"
    bootstrap: "4.3.1"
    font-awesome: "5.11.2"
    smooth-scroll: "14.2.1"
    moment: "2.24.0"
    fuse: "3.4.6"
    lazysizes: "5.2.0"
