# Site core configuration
# See default configuration: https://jekyllrb.com/docs/configuration/default
# /!\ don't override the elements of this configuration in src/_config.yml or src/_config_dev.yml
#     except if you know what you do

# Server

detach: false
show_dir_listing: false
encoding: "utf-8"
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Build

data_dir: "_core/data"
includes_dir: "_core/includes"
layouts_dir: "_core/layouts"
plugins_dir: "_core/plugins"

source: "src"
destination: "dest"

sass:
  sass_dir: "_core/sass"
  style: "compressed"

# Normally files starting by ., #, ~ and _ are ignoring by the Jekyll build.
include:
  - "_static" # project folder for static files
  - "_core" # core folder for static files

# Force to exclude some files for the watcher (with --watch option) in the Jekyll::Watcher
# See https://help.github.jp/enterprise/2.11/user/articles/files-that-start-with-an-underscore-are-missing/
exclude:
  - ".sass-cache"
  - ".jekyll-metadata"
  - ".jekyll-cache"
  - ".jekyll-config-debug.json" # project file for debugging

# Plugins

plugins:
  - "jekyll-sitemap"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-mentions"
  - "jekyll-redirect-from"
  - "jemoji"

# Redirect

redirect_from:
  json: false

# Layout

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
      article: true
      comment: true

# Specific to project core

project_core:
  libs:
    version:
      jquery: "3.4.1"
      popper: "1.14.3"
      bootstrap: "4.3.1"
      font-awesome: "5.11.2"
      smooth-scroll: "14.2.1"
      moment: "2.24.0"
      fuse: "3.4.6"
      lazysizes: "5.2.0"
      mathjax: "2.7.7"
